import { Patient, PatientRepository } from '../repositories/PatientRepository';
import { DuplicateDetectionService } from './DuplicateDetectionService';
import { supabase } from '../supabaseClient';

export class RegistrationService {
  /**
   * Main entry point for registering a new patient securely.
   */
  static async registerPatient(patientData: Patient, identifiers: {type: string, value: string}[], ashaId?: string, isOffline: boolean = false) {
    
    if (!isOffline) {
      // 1. Check for duplicates
      const duplicateConfidence = await DuplicateDetectionService.checkDuplicate(patientData, identifiers);
      
      if (duplicateConfidence === 'HIGH') {
        throw new Error('HIGH_CONFIDENCE_DUPLICATE: A patient with these exact details already exists.');
      } else if (duplicateConfidence === 'UNCERTAIN') {
        // Flag for review, but allow creation for now, or throw a specific error asking for confirmation.
        console.warn('UNCERTAIN_DUPLICATE: Proceeding with caution.');
      }

      // 2. Create the Patient (System ID P-... generated by DB trigger)
      const newPatient = await PatientRepository.createPatient(patientData);

      // 3. Save Identifiers
      if (identifiers.length > 0 && newPatient.id) {
        const identifierInserts = identifiers.map(i => ({
          patient_id: newPatient.id,
          identifier_type: i.type,
          identifier_value: i.value
        }));
        await supabase.from('patient_identifiers').insert(identifierInserts);
      }

      // 4. Assign ASHA if provided
      if (ashaId && newPatient.id) {
        await PatientRepository.assignAsha(newPatient.id, ashaId, 'primary');
      }

      return newPatient;
    } else {
      // OFFLINE REGISTRATION LOGIC
      // Generate a temporary ID that the sync engine will later replace
      const tempId = typeof crypto !== 'undefined' && crypto.randomUUID ? crypto.randomUUID() : 'temp-' + Math.random().toString(36).substring(2);
      const tempPatient = {
        ...patientData,
        id: tempId,
        patient_id: `TEMP-${Date.now()}`
      };
      
      // The useOfflineSync system should intercept this and save it to IndexedDB
      // For now, we return the temp object for the UI to use
      return tempPatient;
    }
  }
}
